name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testsuite:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.3']
        prefer-lowest: ['']
        include:
          - php-version: '8.1'
            prefer-lowest: 'prefer-lowest'

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl
        coverage: pcov

    - name: Get composer cache directory
      id: composercache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Composer install
      run: |
        composer --version
        if ${{ matrix.prefer-lowest == 'prefer-lowest' }}
        then
          composer update --prefer-lowest --prefer-stable
        else
          composer install --no-progress --prefer-dist --optimize-autoloader
        fi
        if ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then composer require --dev dereuromark/composer-prefer-lowest:dev-master; fi

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '8.1' ]]
        then
          vendor/bin/phpunit --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit
        fi

    - name: Validate prefer-lowest
      run: if ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then vendor/bin/validate-prefer-lowest -m; fi

    - name: Code Coverage Report
      if: success() && matrix.php-version == '8.1'
      uses: codecov/codecov-action@v3

  validation:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none

    - name: Get composer cache directory
      id: composercache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Composer Install
      run: composer stan-setup

    - name: Run phpstan
      run: vendor/bin/phpstan analyse --error-format=github

    - name: Run phpcs
      run: composer cs-check
